services:
  - type: web
    name: eazyride-haye-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node src/db/ensureSchema.js && npx prisma db push && node prisma/seed.js && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
